package com.huemedia.cms.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ChatImg generated by hbm2java
 */
@Entity
@Table(name="chat_img"
)
public class ChatImg  implements java.io.Serializable {


     private Integer id;
     private String ticketId;
     private String path;
     private String createBy;
     private Date createDate;

    public ChatImg() {
    }

	
    public ChatImg(String ticketId) {
        this.ticketId = ticketId;
    }
    public ChatImg(String ticketId, String path, String createBy, Date createDate) {
       this.ticketId = ticketId;
       this.path = path;
       this.createBy = createBy;
       this.createDate = createDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="ticket_id", nullable=false, length=50)
    public String getTicketId() {
        return this.ticketId;
    }
    
    public void setTicketId(String ticketId) {
        this.ticketId = ticketId;
    }

    
    @Column(name="path", length=100)
    public String getPath() {
        return this.path;
    }
    
    public void setPath(String path) {
        this.path = path;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }




}


