package com.huemedia.cms.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name="country"
)
public class Country  implements java.io.Serializable {


     private Integer id;
     private String iso;
     private String iso3;
     private String fips;
     private String country;
     private String continent;
     private String currencyCode;
     private String currencyName;
     private String phonePrefix;
     private String postalCode;
     private String languages;
     private String geonameid;
     private String flagActive;
     private Set<Profile> profiles = new HashSet<Profile>(0);
     private Set<Plan> plans = new HashSet<Plan>(0);
     private Set<State> states = new HashSet<State>(0);

    public Country() {
    }

    public Country(String iso, String iso3, String fips, String country, String continent, String currencyCode, String currencyName, String phonePrefix, String postalCode, String languages, String geonameid, String flagActive, Set<Profile> profiles, Set<Plan> plans, Set<State> states) {
       this.iso = iso;
       this.iso3 = iso3;
       this.fips = fips;
       this.country = country;
       this.continent = continent;
       this.currencyCode = currencyCode;
       this.currencyName = currencyName;
       this.phonePrefix = phonePrefix;
       this.postalCode = postalCode;
       this.languages = languages;
       this.geonameid = geonameid;
       this.flagActive = flagActive;
       this.profiles = profiles;
       this.plans = plans;
       this.states = states;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="iso", length=45)
    public String getIso() {
        return this.iso;
    }
    
    public void setIso(String iso) {
        this.iso = iso;
    }

    
    @Column(name="iso3", length=45)
    public String getIso3() {
        return this.iso3;
    }
    
    public void setIso3(String iso3) {
        this.iso3 = iso3;
    }

    
    @Column(name="fips", length=45)
    public String getFips() {
        return this.fips;
    }
    
    public void setFips(String fips) {
        this.fips = fips;
    }

    
    @Column(name="country", length=45)
    public String getCountry() {
        return this.country;
    }
    
    public void setCountry(String country) {
        this.country = country;
    }

    
    @Column(name="continent", length=45)
    public String getContinent() {
        return this.continent;
    }
    
    public void setContinent(String continent) {
        this.continent = continent;
    }

    
    @Column(name="currency_code", length=45)
    public String getCurrencyCode() {
        return this.currencyCode;
    }
    
    public void setCurrencyCode(String currencyCode) {
        this.currencyCode = currencyCode;
    }

    
    @Column(name="currency_name", length=45)
    public String getCurrencyName() {
        return this.currencyName;
    }
    
    public void setCurrencyName(String currencyName) {
        this.currencyName = currencyName;
    }

    
    @Column(name="phone_prefix", length=45)
    public String getPhonePrefix() {
        return this.phonePrefix;
    }
    
    public void setPhonePrefix(String phonePrefix) {
        this.phonePrefix = phonePrefix;
    }

    
    @Column(name="postal_code", length=45)
    public String getPostalCode() {
        return this.postalCode;
    }
    
    public void setPostalCode(String postalCode) {
        this.postalCode = postalCode;
    }

    
    @Column(name="languages", length=45)
    public String getLanguages() {
        return this.languages;
    }
    
    public void setLanguages(String languages) {
        this.languages = languages;
    }

    
    @Column(name="geonameid", length=45)
    public String getGeonameid() {
        return this.geonameid;
    }
    
    public void setGeonameid(String geonameid) {
        this.geonameid = geonameid;
    }

    
    @Column(name="flag_active", length=1)
    public String getFlagActive() {
        return this.flagActive;
    }
    
    public void setFlagActive(String flagActive) {
        this.flagActive = flagActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Profile> getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<Plan> getPlans() {
        return this.plans;
    }
    
    public void setPlans(Set<Plan> plans) {
        this.plans = plans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="country")
    public Set<State> getStates() {
        return this.states;
    }
    
    public void setStates(Set<State> states) {
        this.states = states;
    }




}


