package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name="group"
)
public class Group  implements java.io.Serializable {


     private String id;
     private String name;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<Unit> units = new HashSet<Unit>(0);
     private Set<TicketGroup> ticketGroups = new HashSet<TicketGroup>(0);
     private Set<TicketAssignment> ticketAssignments = new HashSet<TicketAssignment>(0);
     private Set<StaffGroup> staffGroups = new HashSet<StaffGroup>(0);
     private Set<SlaEscalation> slaEscalations = new HashSet<SlaEscalation>(0);

    public Group() {
    }

	
    public Group(String id) {
        this.id = id;
    }
    public Group(String id, String name, String createBy, Date createDate, String updateBy, Date updateDate, Set<Unit> units, Set<TicketGroup> ticketGroups, Set<TicketAssignment> ticketAssignments, Set<StaffGroup> staffGroups, Set<SlaEscalation> slaEscalations) {
       this.id = id;
       this.name = name;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.units = units;
       this.ticketGroups = ticketGroups;
       this.ticketAssignments = ticketAssignments;
       this.staffGroups = staffGroups;
       this.slaEscalations = slaEscalations;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<Unit> getUnits() {
        return this.units;
    }
    
    public void setUnits(Set<Unit> units) {
        this.units = units;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<TicketGroup> getTicketGroups() {
        return this.ticketGroups;
    }
    
    public void setTicketGroups(Set<TicketGroup> ticketGroups) {
        this.ticketGroups = ticketGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<TicketAssignment> getTicketAssignments() {
        return this.ticketAssignments;
    }
    
    public void setTicketAssignments(Set<TicketAssignment> ticketAssignments) {
        this.ticketAssignments = ticketAssignments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<StaffGroup> getStaffGroups() {
        return this.staffGroups;
    }
    
    public void setStaffGroups(Set<StaffGroup> staffGroups) {
        this.staffGroups = staffGroups;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="group")
    public Set<SlaEscalation> getSlaEscalations() {
        return this.slaEscalations;
    }
    
    public void setSlaEscalations(Set<SlaEscalation> slaEscalations) {
        this.slaEscalations = slaEscalations;
    }




}


