package com.huemedia.cms.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * KnowledgeFile generated by hbm2java
 */
@Entity
@Table(name="knowledge_file"
)
public class KnowledgeFile  implements java.io.Serializable {


     private Integer id;
     private Knowledge knowledge;
     private String name;
     private String description;
     private String mime;
     private Long size;
     private byte[] data;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;

    public KnowledgeFile() {
    }

	
    public KnowledgeFile(Knowledge knowledge) {
        this.knowledge = knowledge;
    }
    public KnowledgeFile(Knowledge knowledge, String name, String description, String mime, Long size, byte[] data, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.knowledge = knowledge;
       this.name = name;
       this.description = description;
       this.mime = mime;
       this.size = size;
       this.data = data;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="knowledge_id", nullable=false)
    public Knowledge getKnowledge() {
        return this.knowledge;
    }
    
    public void setKnowledge(Knowledge knowledge) {
        this.knowledge = knowledge;
    }

    
    @Column(name="name")
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="mime", length=50)
    public String getMime() {
        return this.mime;
    }
    
    public void setMime(String mime) {
        this.mime = mime;
    }

    
    @Column(name="size")
    public Long getSize() {
        return this.size;
    }
    
    public void setSize(Long size) {
        this.size = size;
    }

    
    @Column(name="data")
    public byte[] getData() {
        return this.data;
    }
    
    public void setData(byte[] data) {
        this.data = data;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


