package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Knowledge generated by hbm2java
 */
@Entity
@Table(name="knowledge"
)
public class Knowledge  implements java.io.Serializable {


     private Integer id;
     private KnowledgeCategory knowledgeCategory;
     private String title;
     private String description;
     private String solution;
     private Boolean staffOnly;
     private Boolean approved;
     private String status;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<KnowledgeFile> knowledgeFiles = new HashSet<KnowledgeFile>(0);

    public Knowledge() {
    }

    public Knowledge(KnowledgeCategory knowledgeCategory, String title, String description, String solution, Boolean staffOnly, Boolean approved, String status, String createBy, Date createDate, String updateBy, Date updateDate, Set<KnowledgeFile> knowledgeFiles) {
       this.knowledgeCategory = knowledgeCategory;
       this.title = title;
       this.description = description;
       this.solution = solution;
       this.staffOnly = staffOnly;
       this.approved = approved;
       this.status = status;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.knowledgeFiles = knowledgeFiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="knowledge_category")
    public KnowledgeCategory getKnowledgeCategory() {
        return this.knowledgeCategory;
    }
    
    public void setKnowledgeCategory(KnowledgeCategory knowledgeCategory) {
        this.knowledgeCategory = knowledgeCategory;
    }

    
    @Column(name="title", length=200)
    public String getTitle() {
        return this.title;
    }
    
    public void setTitle(String title) {
        this.title = title;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="solution")
    public String getSolution() {
        return this.solution;
    }
    
    public void setSolution(String solution) {
        this.solution = solution;
    }

    
    @Column(name="staff_only")
    public Boolean getStaffOnly() {
        return this.staffOnly;
    }
    
    public void setStaffOnly(Boolean staffOnly) {
        this.staffOnly = staffOnly;
    }

    
    @Column(name="approved")
    public Boolean getApproved() {
        return this.approved;
    }
    
    public void setApproved(Boolean approved) {
        this.approved = approved;
    }

    
    @Column(name="status", length=50)
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="knowledge")
    public Set<KnowledgeFile> getKnowledgeFiles() {
        return this.knowledgeFiles;
    }
    
    public void setKnowledgeFiles(Set<KnowledgeFile> knowledgeFiles) {
        this.knowledgeFiles = knowledgeFiles;
    }




}


