package com.huemedia.cms.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Period generated by hbm2java
 */
@Entity
@Table(name="period"
)
public class Period  implements java.io.Serializable {


     private Integer id;
     private String rangeName;
     private String rangeFrom;
     private String rangeTo;

    public Period() {
    }

	
    public Period(Integer id, String rangeName, String rangeFrom) {
        this.id = id;
        this.rangeName = rangeName;
        this.rangeFrom = rangeFrom;
    }
    public Period(Integer id, String rangeName, String rangeFrom, String rangeTo) {
       this.id = id;
       this.rangeName = rangeName;
       this.rangeFrom = rangeFrom;
       this.rangeTo = rangeTo;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="range_name", nullable=false, length=10)
    public String getRangeName() {
        return this.rangeName;
    }
    
    public void setRangeName(String rangeName) {
        this.rangeName = rangeName;
    }

    
    @Column(name="range_from", nullable=false, length=5)
    public String getRangeFrom() {
        return this.rangeFrom;
    }
    
    public void setRangeFrom(String rangeFrom) {
        this.rangeFrom = rangeFrom;
    }

    
    @Column(name="range_to", length=5)
    public String getRangeTo() {
        return this.rangeTo;
    }
    
    public void setRangeTo(String rangeTo) {
        this.rangeTo = rangeTo;
    }




}


