package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Priority generated by hbm2java
 */
@Entity
@Table(name="priority"
)
public class Priority  implements java.io.Serializable {


     private String id;
     private String name;
     private Integer rank;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<SlaEscalation> slaEscalations = new HashSet<SlaEscalation>(0);
     private Set<Ticket> tickets = new HashSet<Ticket>(0);

    public Priority() {
    }

	
    public Priority(String id) {
        this.id = id;
    }
    public Priority(String id, String name, Integer rank, String createBy, Date createDate, String updateBy, Date updateDate, Set<SlaEscalation> slaEscalations, Set<Ticket> tickets) {
       this.id = id;
       this.name = name;
       this.rank = rank;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.slaEscalations = slaEscalations;
       this.tickets = tickets;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="rank")
    public Integer getRank() {
        return this.rank;
    }
    
    public void setRank(Integer rank) {
        this.rank = rank;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priority")
    public Set<SlaEscalation> getSlaEscalations() {
        return this.slaEscalations;
    }
    
    public void setSlaEscalations(Set<SlaEscalation> slaEscalations) {
        this.slaEscalations = slaEscalations;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="priority")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }




}


