package com.huemedia.cms.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Rangecount generated by hbm2java
 */
@Entity
@Table(name="rangecount"
)
public class Rangecount  implements java.io.Serializable {


     private String name;
     private Integer id;

    public Rangecount() {
    }

    public Rangecount(String name, Integer id) {
       this.name = name;
       this.id = id;
    }
   
     @Id 

    
    @Column(name="name", unique=true, nullable=false, length=50)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="id", nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }




}


