package com.huemedia.cms.model.entity;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Sequence generated by hbm2java
 */
@Entity
@Table(name="sequence"
)
public class Sequence  implements java.io.Serializable {


     private Integer id;
     private String prefix;
     private Integer year;
     private Integer month;
     private Integer no;

    public Sequence() {
    }

    public Sequence(String prefix, Integer year, Integer month, Integer no) {
       this.prefix = prefix;
       this.year = year;
       this.month = month;
       this.no = no;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    
    @Column(name="prefix", length=50)
    public String getPrefix() {
        return this.prefix;
    }
    
    public void setPrefix(String prefix) {
        this.prefix = prefix;
    }

    
    @Column(name="year")
    public Integer getYear() {
        return this.year;
    }
    
    public void setYear(Integer year) {
        this.year = year;
    }

    
    @Column(name="month")
    public Integer getMonth() {
        return this.month;
    }
    
    public void setMonth(Integer month) {
        this.month = month;
    }

    
    @Column(name="no")
    public Integer getNo() {
        return this.no;
    }
    
    public void setNo(Integer no) {
        this.no = no;
    }




}


