package com.huemedia.cms.model.entity;


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * SlaEscalation generated by hbm2java
 */
@Entity
@Table(name="sla_escalation"
)
public class SlaEscalation  implements java.io.Serializable {


     private Integer id;
     private Status status;
     private Group group;
     private Sla sla;
     private Priority priority;
     private Escalation escalation;
     private Boolean sendToOwner;
     private Boolean sendToAssignee;
     private Boolean sendToSupervisor;
     private String sendTo;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;

    public SlaEscalation() {
    }

    public SlaEscalation(Status status, Group group, Sla sla, Priority priority, Escalation escalation, Boolean sendToOwner, Boolean sendToAssignee, Boolean sendToSupervisor, String sendTo, String createBy, Date createDate, String updateBy, Date updateDate) {
       this.status = status;
       this.group = group;
       this.sla = sla;
       this.priority = priority;
       this.escalation = escalation;
       this.sendToOwner = sendToOwner;
       this.sendToAssignee = sendToAssignee;
       this.sendToSupervisor = sendToSupervisor;
       this.sendTo = sendTo;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id")
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="sla_id")
    public Sla getSla() {
        return this.sla;
    }
    
    public void setSla(Sla sla) {
        this.sla = sla;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priority")
    public Priority getPriority() {
        return this.priority;
    }
    
    public void setPriority(Priority priority) {
        this.priority = priority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="escalation_id")
    public Escalation getEscalation() {
        return this.escalation;
    }
    
    public void setEscalation(Escalation escalation) {
        this.escalation = escalation;
    }

    
    @Column(name="send_to_owner")
    public Boolean getSendToOwner() {
        return this.sendToOwner;
    }
    
    public void setSendToOwner(Boolean sendToOwner) {
        this.sendToOwner = sendToOwner;
    }

    
    @Column(name="send_to_assignee")
    public Boolean getSendToAssignee() {
        return this.sendToAssignee;
    }
    
    public void setSendToAssignee(Boolean sendToAssignee) {
        this.sendToAssignee = sendToAssignee;
    }

    
    @Column(name="send_to_supervisor")
    public Boolean getSendToSupervisor() {
        return this.sendToSupervisor;
    }
    
    public void setSendToSupervisor(Boolean sendToSupervisor) {
        this.sendToSupervisor = sendToSupervisor;
    }

    
    @Column(name="send_to", length=65535)
    public String getSendTo() {
        return this.sendTo;
    }
    
    public void setSendTo(String sendTo) {
        this.sendTo = sendTo;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }




}


