package com.huemedia.cms.model.entity;


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name="state"
)
public class State  implements java.io.Serializable {


     private Integer id;
     private Country country;
     private String name;
     private String timezone;
     private String flagActive;
     private Set<Plan> plans = new HashSet<Plan>(0);
     private Set<Profile> profiles = new HashSet<Profile>(0);

    public State() {
    }

    public State(Country country, String name, String timezone, String flagActive, Set<Plan> plans, Set<Profile> profiles) {
       this.country = country;
       this.name = name;
       this.timezone = timezone;
       this.flagActive = flagActive;
       this.plans = plans;
       this.profiles = profiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="region_id")
    public Country getCountry() {
        return this.country;
    }
    
    public void setCountry(Country country) {
        this.country = country;
    }

    
    @Column(name="name", length=45)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="timezone", length=45)
    public String getTimezone() {
        return this.timezone;
    }
    
    public void setTimezone(String timezone) {
        this.timezone = timezone;
    }

    
    @Column(name="flag_active", length=1)
    public String getFlagActive() {
        return this.flagActive;
    }
    
    public void setFlagActive(String flagActive) {
        this.flagActive = flagActive;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="state")
    public Set<Plan> getPlans() {
        return this.plans;
    }
    
    public void setPlans(Set<Plan> plans) {
        this.plans = plans;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="state")
    public Set<Profile> getProfiles() {
        return this.profiles;
    }
    
    public void setProfiles(Set<Profile> profiles) {
        this.profiles = profiles;
    }




}


