package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TicketActivity generated by hbm2java
 */
@Entity
@Table(name="ticket_activity"
)
public class TicketActivity  implements java.io.Serializable {


     private Integer id;
     private ActivityType activityType;
     private Ticket ticket;
     private TicketAssignment ticketAssignment;
     private Date date;
     private Date startTime;
     private Date endTime;
     private String location;
     private String agenda;
     private String description;
     private Boolean sendEmail;
     private String sendTo;
     private String subject;
     private String message;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<ActivityFile> activityFiles = new HashSet<ActivityFile>(0);

    public TicketActivity() {
    }

	
    public TicketActivity(Ticket ticket) {
        this.ticket = ticket;
    }
    public TicketActivity(ActivityType activityType, Ticket ticket, TicketAssignment ticketAssignment, Date date, Date startTime, Date endTime, String location, String agenda, String description, Boolean sendEmail, String sendTo, String subject, String message, String createBy, Date createDate, String updateBy, Date updateDate, Set<ActivityFile> activityFiles) {
       this.activityType = activityType;
       this.ticket = ticket;
       this.ticketAssignment = ticketAssignment;
       this.date = date;
       this.startTime = startTime;
       this.endTime = endTime;
       this.location = location;
       this.agenda = agenda;
       this.description = description;
       this.sendEmail = sendEmail;
       this.sendTo = sendTo;
       this.subject = subject;
       this.message = message;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.activityFiles = activityFiles;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="activity_type")
    public ActivityType getActivityType() {
        return this.activityType;
    }
    
    public void setActivityType(ActivityType activityType) {
        this.activityType = activityType;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ticket_id", nullable=false)
    public Ticket getTicket() {
        return this.ticket;
    }
    
    public void setTicket(Ticket ticket) {
        this.ticket = ticket;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="assignment_id")
    public TicketAssignment getTicketAssignment() {
        return this.ticketAssignment;
    }
    
    public void setTicketAssignment(TicketAssignment ticketAssignment) {
        this.ticketAssignment = ticketAssignment;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="date", length=10)
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="start_time", length=19)
    public Date getStartTime() {
        return this.startTime;
    }
    
    public void setStartTime(Date startTime) {
        this.startTime = startTime;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="end_time", length=19)
    public Date getEndTime() {
        return this.endTime;
    }
    
    public void setEndTime(Date endTime) {
        this.endTime = endTime;
    }

    
    @Column(name="location", length=100)
    public String getLocation() {
        return this.location;
    }
    
    public void setLocation(String location) {
        this.location = location;
    }

    
    @Column(name="agenda", length=100)
    public String getAgenda() {
        return this.agenda;
    }
    
    public void setAgenda(String agenda) {
        this.agenda = agenda;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="send_email")
    public Boolean getSendEmail() {
        return this.sendEmail;
    }
    
    public void setSendEmail(Boolean sendEmail) {
        this.sendEmail = sendEmail;
    }

    
    @Column(name="send_to")
    public String getSendTo() {
        return this.sendTo;
    }
    
    public void setSendTo(String sendTo) {
        this.sendTo = sendTo;
    }

    
    @Column(name="subject", length=200)
    public String getSubject() {
        return this.subject;
    }
    
    public void setSubject(String subject) {
        this.subject = subject;
    }

    
    @Column(name="message")
    public String getMessage() {
        return this.message;
    }
    
    public void setMessage(String message) {
        this.message = message;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticketActivity")
    public Set<ActivityFile> getActivityFiles() {
        return this.activityFiles;
    }
    
    public void setActivityFiles(Set<ActivityFile> activityFiles) {
        this.activityFiles = activityFiles;
    }




}


