package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TicketGroup generated by hbm2java
 */
@Entity
@Table(name="ticket_group"
)
public class TicketGroup  implements java.io.Serializable {


     private Integer id;
     private Group group;
     private String name;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<Ticket> tickets = new HashSet<Ticket>(0);
     private Set<TicketCategory> ticketCategories = new HashSet<TicketCategory>(0);
     private Set<TicketAssignment> ticketAssignments = new HashSet<TicketAssignment>(0);

    public TicketGroup() {
    }

    public TicketGroup(Group group, String name, String createBy, Date createDate, String updateBy, Date updateDate, Set<Ticket> tickets, Set<TicketCategory> ticketCategories, Set<TicketAssignment> ticketAssignments) {
       this.group = group;
       this.name = name;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.tickets = tickets;
       this.ticketCategories = ticketCategories;
       this.ticketAssignments = ticketAssignments;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id")
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticketGroup")
    public Set<Ticket> getTickets() {
        return this.tickets;
    }
    
    public void setTickets(Set<Ticket> tickets) {
        this.tickets = tickets;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticketGroup")
    public Set<TicketCategory> getTicketCategories() {
        return this.ticketCategories;
    }
    
    public void setTicketCategories(Set<TicketCategory> ticketCategories) {
        this.ticketCategories = ticketCategories;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticketGroup")
    public Set<TicketAssignment> getTicketAssignments() {
        return this.ticketAssignments;
    }
    
    public void setTicketAssignments(Set<TicketAssignment> ticketAssignments) {
        this.ticketAssignments = ticketAssignments;
    }




}


