package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Ticket generated by hbm2java
 */
@Entity
@Table(name="ticket"
)
public class Ticket  implements java.io.Serializable {


     private String id;
     private Originator originator;
     private Status status;
     private TicketCategory ticketCategory;
     private Rating rating;
     private Profile profile;
     private TicketGroup ticketGroup;
     private Priority priority;
     private Category category;
     private String ticketTitle;
     private String ticketType;
     private String description;
     private String action;
     private String remarks;
     private Date assignDate;
     private Date replyDate;
     private Date resolutionDate;
     private Date lastStatusUpdate;
     private String groupId;
     private Integer regionId;
     private Integer assigneeId;
     private Integer supervisorId;
     private Integer duration;
     private String intervalX;
     private String comment;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<TicketAssignment> ticketAssignments = new HashSet<TicketAssignment>(0);
     private Set<SlaTask> slaTasks = new HashSet<SlaTask>(0);
     private Set<TicketActivity> ticketActivities = new HashSet<TicketActivity>(0);
     private Set<TicketFile> ticketFiles = new HashSet<TicketFile>(0);

    public Ticket() {
    }

	
    public Ticket(String id) {
        this.id = id;
    }
    public Ticket(String id, Originator originator, Status status, TicketCategory ticketCategory, Rating rating, Profile profile, TicketGroup ticketGroup, Priority priority, Category category, String ticketTitle, String ticketType, String description, String action, String remarks, Date assignDate, Date replyDate, Date resolutionDate, Date lastStatusUpdate, String groupId, Integer regionId, Integer assigneeId, Integer supervisorId, Integer duration, String intervalX, String comment, String createBy, Date createDate, String updateBy, Date updateDate, Set<TicketAssignment> ticketAssignments, Set<SlaTask> slaTasks, Set<TicketActivity> ticketActivities, Set<TicketFile> ticketFiles) {
       this.id = id;
       this.originator = originator;
       this.status = status;
       this.ticketCategory = ticketCategory;
       this.rating = rating;
       this.profile = profile;
       this.ticketGroup = ticketGroup;
       this.priority = priority;
       this.category = category;
       this.ticketTitle = ticketTitle;
       this.ticketType = ticketType;
       this.description = description;
       this.action = action;
       this.remarks = remarks;
       this.assignDate = assignDate;
       this.replyDate = replyDate;
       this.resolutionDate = resolutionDate;
       this.lastStatusUpdate = lastStatusUpdate;
       this.groupId = groupId;
       this.regionId = regionId;
       this.assigneeId = assigneeId;
       this.supervisorId = supervisorId;
       this.duration = duration;
       this.intervalX = intervalX;
       this.comment = comment;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.ticketAssignments = ticketAssignments;
       this.slaTasks = slaTasks;
       this.ticketActivities = ticketActivities;
       this.ticketFiles = ticketFiles;
    }
   
     @Id 

    
    @Column(name="id", unique=true, nullable=false, length=50)
    public String getId() {
        return this.id;
    }
    
    public void setId(String id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="originator")
    public Originator getOriginator() {
        return this.originator;
    }
    
    public void setOriginator(Originator originator) {
        this.originator = originator;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="status")
    public Status getStatus() {
        return this.status;
    }
    
    public void setStatus(Status status) {
        this.status = status;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ticket_category")
    public TicketCategory getTicketCategory() {
        return this.ticketCategory;
    }
    
    public void setTicketCategory(TicketCategory ticketCategory) {
        this.ticketCategory = ticketCategory;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="rating_id")
    public Rating getRating() {
        return this.rating;
    }
    
    public void setRating(Rating rating) {
        this.rating = rating;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="profile_id")
    public Profile getProfile() {
        return this.profile;
    }
    
    public void setProfile(Profile profile) {
        this.profile = profile;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ticket_group")
    public TicketGroup getTicketGroup() {
        return this.ticketGroup;
    }
    
    public void setTicketGroup(TicketGroup ticketGroup) {
        this.ticketGroup = ticketGroup;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="priority")
    public Priority getPriority() {
        return this.priority;
    }
    
    public void setPriority(Priority priority) {
        this.priority = priority;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="category")
    public Category getCategory() {
        return this.category;
    }
    
    public void setCategory(Category category) {
        this.category = category;
    }

    
    @Column(name="ticket_title", length=200)
    public String getTicketTitle() {
        return this.ticketTitle;
    }
    
    public void setTicketTitle(String ticketTitle) {
        this.ticketTitle = ticketTitle;
    }

    
    @Column(name="ticket_type", length=1)
    public String getTicketType() {
        return this.ticketType;
    }
    
    public void setTicketType(String ticketType) {
        this.ticketType = ticketType;
    }

    
    @Column(name="description")
    public String getDescription() {
        return this.description;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }

    
    @Column(name="action")
    public String getAction() {
        return this.action;
    }
    
    public void setAction(String action) {
        this.action = action;
    }

    
    @Column(name="remarks", length=200)
    public String getRemarks() {
        return this.remarks;
    }
    
    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="assign_date", length=19)
    public Date getAssignDate() {
        return this.assignDate;
    }
    
    public void setAssignDate(Date assignDate) {
        this.assignDate = assignDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="reply_date", length=19)
    public Date getReplyDate() {
        return this.replyDate;
    }
    
    public void setReplyDate(Date replyDate) {
        this.replyDate = replyDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="resolution_date", length=19)
    public Date getResolutionDate() {
        return this.resolutionDate;
    }
    
    public void setResolutionDate(Date resolutionDate) {
        this.resolutionDate = resolutionDate;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="last_status_update", length=19)
    public Date getLastStatusUpdate() {
        return this.lastStatusUpdate;
    }
    
    public void setLastStatusUpdate(Date lastStatusUpdate) {
        this.lastStatusUpdate = lastStatusUpdate;
    }

    
    @Column(name="group_id", length=50)
    public String getGroupId() {
        return this.groupId;
    }
    
    public void setGroupId(String groupId) {
        this.groupId = groupId;
    }

    
    @Column(name="region_id")
    public Integer getRegionId() {
        return this.regionId;
    }
    
    public void setRegionId(Integer regionId) {
        this.regionId = regionId;
    }

    
    @Column(name="assignee_id")
    public Integer getAssigneeId() {
        return this.assigneeId;
    }
    
    public void setAssigneeId(Integer assigneeId) {
        this.assigneeId = assigneeId;
    }

    
    @Column(name="supervisor_id")
    public Integer getSupervisorId() {
        return this.supervisorId;
    }
    
    public void setSupervisorId(Integer supervisorId) {
        this.supervisorId = supervisorId;
    }

    
    @Column(name="duration")
    public Integer getDuration() {
        return this.duration;
    }
    
    public void setDuration(Integer duration) {
        this.duration = duration;
    }

    
    @Column(name="interval_x", length=100)
    public String getIntervalX() {
        return this.intervalX;
    }
    
    public void setIntervalX(String intervalX) {
        this.intervalX = intervalX;
    }

    
    @Column(name="comment", length=500)
    public String getComment() {
        return this.comment;
    }
    
    public void setComment(String comment) {
        this.comment = comment;
    }

    
    @Column(name="create_by", length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<TicketAssignment> getTicketAssignments() {
        return this.ticketAssignments;
    }
    
    public void setTicketAssignments(Set<TicketAssignment> ticketAssignments) {
        this.ticketAssignments = ticketAssignments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<SlaTask> getSlaTasks() {
        return this.slaTasks;
    }
    
    public void setSlaTasks(Set<SlaTask> slaTasks) {
        this.slaTasks = slaTasks;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<TicketActivity> getTicketActivities() {
        return this.ticketActivities;
    }
    
    public void setTicketActivities(Set<TicketActivity> ticketActivities) {
        this.ticketActivities = ticketActivities;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="ticket")
    public Set<TicketFile> getTicketFiles() {
        return this.ticketFiles;
    }
    
    public void setTicketFiles(Set<TicketFile> ticketFiles) {
        this.ticketFiles = ticketFiles;
    }




}


