package com.huemedia.cms.model.entity;


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Unit generated by hbm2java
 */
@Entity
@Table(name="unit"
)
public class Unit  implements java.io.Serializable {


     private Integer id;
     private Group group;
     private String name;
     private String createBy;
     private Date createDate;
     private String updateBy;
     private Date updateDate;
     private Set<TicketAssignment> ticketAssignments = new HashSet<TicketAssignment>(0);
     private Set<StaffGroup> staffGroups = new HashSet<StaffGroup>(0);

    public Unit() {
    }

	
    public Unit(Group group, String name, String createBy, Date createDate, String updateBy, Date updateDate) {
        this.group = group;
        this.name = name;
        this.createBy = createBy;
        this.createDate = createDate;
        this.updateBy = updateBy;
        this.updateDate = updateDate;
    }
    public Unit(Group group, String name, String createBy, Date createDate, String updateBy, Date updateDate, Set<TicketAssignment> ticketAssignments, Set<StaffGroup> staffGroups) {
       this.group = group;
       this.name = name;
       this.createBy = createBy;
       this.createDate = createDate;
       this.updateBy = updateBy;
       this.updateDate = updateDate;
       this.ticketAssignments = ticketAssignments;
       this.staffGroups = staffGroups;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="group_id", nullable=false)
    public Group getGroup() {
        return this.group;
    }
    
    public void setGroup(Group group) {
        this.group = group;
    }

    
    @Column(name="name", nullable=false, length=500)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="create_by", nullable=false, length=50)
    public String getCreateBy() {
        return this.createBy;
    }
    
    public void setCreateBy(String createBy) {
        this.createBy = createBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="create_date", nullable=false, length=19)
    public Date getCreateDate() {
        return this.createDate;
    }
    
    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    
    @Column(name="update_by", nullable=false, length=50)
    public String getUpdateBy() {
        return this.updateBy;
    }
    
    public void setUpdateBy(String updateBy) {
        this.updateBy = updateBy;
    }

    @Temporal(TemporalType.TIMESTAMP)
    @Column(name="update_date", nullable=false, length=19)
    public Date getUpdateDate() {
        return this.updateDate;
    }
    
    public void setUpdateDate(Date updateDate) {
        this.updateDate = updateDate;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<TicketAssignment> getTicketAssignments() {
        return this.ticketAssignments;
    }
    
    public void setTicketAssignments(Set<TicketAssignment> ticketAssignments) {
        this.ticketAssignments = ticketAssignments;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="unit")
    public Set<StaffGroup> getStaffGroups() {
        return this.staffGroups;
    }
    
    public void setStaffGroups(Set<StaffGroup> staffGroups) {
        this.staffGroups = staffGroups;
    }




}


